apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-test
  template:
    metadata:
      labels:
        app: jenkins-test
    spec:
      containers:
        - name: jenkins-test
          image: anildcoder/jenkins-test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080